### ISSUE TITLE
[Feature Request] Add Support for Custom Animals

### ISSUE THREAD

**Issue by codewithbjim** [Tdue21/Valheim.ShowPregnancy#1]

**Comment by Tdue21** [comment]
This will not be possible without knowning the internal names of said animals. So, in order to support custom animals, I would need to know the specific mods that include them. 

Of course, there may be another way, but that is how it is done right now :D

**Comment by codewithbjim** [comment]
I've checked how you added the animal prefabs, do you think it would be possible to add it thru config? Seeing as the implementation in the code is just a list of strings. So maybe we could comma, or perhaps semicolon separate the names?

**Comment by Tdue21** [comment]
Hmm. That's a good idea. That could probably work.

**Comment by codewithbjim** [comment]
Not sure if this is right as I haven't done that much C# coding and Unity modding.
![image](https://user-images.githubusercontent.com/19782129/170929186-043323de-c6cf-4a39-8d7f-b2d31a0b42d5.png)

**Comment by Tdue21** [comment]
It doesn't look bad ;)

**Comment by codewithbjim** [comment]
I have no experience testing the code in-game. I'll ask around on how to generate a dll to test if it works.

**Comment by codewithbjim** [comment]
It worked! Though I have to change some lines.

![image](https://user-images.githubusercontent.com/19782129/171033346-52786da7-8aea-4812-91af-5926f8356c16.png)

Update:
![image](https://user-images.githubusercontent.com/19782129/171033733-a495ee57-4b84-48ff-8092-0c8b7772cd5a.png)

**Comment by codewithbjim** [comment]
I'll make a PR.

**Comment by Tdue21** [comment]
Cool. I'll take a look and merge it in, if I am happy with your additions :)
I don't see why not though :)
